export const characterData = {
  '어보미네이션': { slug: 'abomination', originType: '일반캐', acquisitionType: '수정캐', upgradeLevel: '3티' },
  '앱소빙 맨': { slug: 'absorbingman', originType: '일반캐', upgradeLevel: '각초' },
  '아담 워록': { slug: 'adamwarlock', originType: '태생캐 (2티, 더블)', acquisitionType: '수정캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '에어로': { slug: 'aero', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '에인션트 원': { slug: 'ancientone', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '안젤라': { slug: 'angela', originType: '일반캐', upgradeLevel: '각초' },
  '아메리카 차베스': { slug: 'americachavez', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '안티맨': { slug: 'antiman', originType: '태생캐 (2티)', upgradeLevel: '3티' },
  '앤트맨': { slug: 'antman', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '아포칼립스': { slug: 'apocalypse', originType: '태생캐 (2티, 더블)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '아라크나이트': { slug: 'arachknight', originType: '일반캐', acquisitionType: '수정캐', upgradeLevel: '각초' },
  '아레스': { slug: 'ares', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '모르도 남작': { slug: 'baronmordo', originType: '일반캐', upgradeLevel: '각초' },
  '바론 제모': { slug: 'baronzemo', originType: '일반캐', acquisitionType: '매생/매엑' },
  '비스트': { slug: 'beast', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '베타 레이 빌': { slug: 'betaraybill', originType: '태생캐 (2티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '비숍': { slug: 'bishop', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '블랙 볼트': { slug: 'blackbolt', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '블랙 캣': { slug: 'blackcat', originType: '일반캐', upgradeLevel: '각초' },
  '블랙 드워프': { slug: 'blackdwarf', originType: '태생캐 (2티)', upgradeLevel: '각초' },
  '블랙 팬서': { slug: 'blackpanther', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '블랙 위도우': { slug: 'blackwidow', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '블랙 스완': { slug: 'blackswan', originType: '태생캐 (3티)', upgradeLevel: '3티' },
  '블레이드': { slug: 'blade', originType: '일반캐', upgradeLevel: '3티' },
  '블루 드래곤': { slug: 'bluedragon', originType: '일반캐', acquisitionType: '수정캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '블루 마블': { slug: 'bluemarvel', originType: '일반캐', upgradeLevel: '3티' },
  '불스아이': { slug: 'bullseye', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '케이블': { slug: 'cable', originType: '태생캐 (2티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '캡틴 아메리카': { slug: 'captainamerica', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '캡틴 마블': { slug: 'captainmarvel', originType: '일반캐', ctp: '파괴', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '카니지': { slug: 'carnage', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '클레아': { slug: 'clea', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '콜로서스': { slug: 'colossus', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '콜버스 글레이브': { slug: 'corvusglaive', originType: '태생캐 (2티)', upgradeLevel: '각초' },
  '크레센트': { slug: 'crescent', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '크로스본즈': { slug: 'crossbones', originType: '일반캐', upgradeLevel: '각초' },
  '크리스탈': { slug: 'crystal', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '사이클롭스': { slug: 'cyclops', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '데이지 존슨': { slug: 'daisyjohnson', originType: '일반캐', upgradeLevel: '각초' },
  '다켄': { slug: 'daken', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '데어데블': { slug: 'daredevil', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '다크호크': { slug: 'darkhawk', originType: '일반캐', upgradeLevel: '2티' },
  '대즐러': { slug: 'dazzler', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '데드풀': { slug: 'deadpool', originType: '태생캐 (2티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '데쓰록': { slug: 'deathlok', originType: '일반캐', upgradeLevel: '2티' },
  '디스트로이어': { slug: 'destroyer', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '닥터 둠': { slug: 'doctordoom', originType: '태생캐 (2티, 더블)', acquisitionType: '엑조디아', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '닥터 옥토퍼스': { slug: 'doctoroctopus', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '닥터 스트레인지': { slug: 'doctorstrange', originType: '태생캐 (2티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '닥터 부두': { slug: 'doctorvoodoo', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '도미노': { slug: 'domino', originType: '일반캐', upgradeLevel: '각초' },
  '도르마무': { slug: 'dormammu', originType: '태생캐 (2티, 더블)', upgradeLevel: '3티' },
  '드랙스': { slug: 'drax', originType: '일반캐', upgradeLevel: '각초' },
  '에보니 모': { slug: 'ebonymaw', originType: '태생캐 (2티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '에이전트 베놈': { slug: 'agentvenom', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '에코': { slug: 'echo', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '엔젤': { slug: 'angel', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '일렉트로': { slug: 'electro', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '엘렉트라': { slug: 'elektra', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '엘사 블러드스톤': { slug: 'elsabloodstone', originType: '일반캐', upgradeLevel: '각초' },
  '엠마 프로스트': { slug: 'emmafrost', originType: '일반캐', acquisitionType: '수정캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '인챈트리스': { slug: 'enchantress', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '팔콘': { slug: 'falcon', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '팬드럴': { slug: 'fandral', originType: '일반캐', upgradeLevel: '각초' },
  '판토맥스': { slug: 'fantomex', originType: '일반캐', upgradeLevel: '각초' },
  '갬빗': { slug: 'gambit', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '가모라': { slug: 'gamora', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '고스트': { slug: 'ghost', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '고스트 팬서': { slug: 'ghostpanther', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '고스트 라이더': { slug: 'ghostrider', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '고르곤': { slug: 'gorgon', originType: '일반캐', upgradeLevel: '각초' },
  '자이언트맨': { slug: 'giantman', originType: '일반캐', upgradeLevel: '각초' },
  '길가메시': { slug: 'gilgamesh', originType: '일반캐', acquisitionType: '디럭스', upgradeLevel: '각초' },
  '글래디에이터': { slug: 'gladiator', originType: '태생캐 (2티, 더블)', acquisitionType: '엑조디아', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '골리앗': { slug: 'goliath', originType: '일반캐', upgradeLevel: '각초' },
  '고르': { slug: 'gorr', originType: '태생캐 (3티)', upgradeLevel: '3티' },
  '고릴라맨': { slug: 'gorillaman', originType: '일반캐', upgradeLevel: '각초' },
  '그린 고블린': { slug: 'greengoblin', originType: '일반캐', upgradeLevel: '3티' },
  '그루트': { slug: 'groot', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '그웬풀': { slug: 'gwenpool', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '호크아이': { slug: 'hawkeye', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '헤임달': { slug: 'heimdall', originType: '일반캐', upgradeLevel: '각초' },
  '헬라': { slug: 'hela', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '헬캣': { slug: 'hellcat', originType: '일반캐', upgradeLevel: '각초' },
  '헬스톰': { slug: 'hellstorm', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '호건': { slug: 'hogun', originType: '일반캐', upgradeLevel: '각초' },
  '헐크': { slug: 'hulk', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '헐크버스터': { slug: 'hulkbuster', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '헐클링': { slug: 'hulkling', originType: '일반캐', upgradeLevel: '각초' },
  '휴먼 토치': { slug: 'humantorch', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '하이드로맨': { slug: 'hydroman', originType: '일반캐', upgradeLevel: '각초' },
  '하이페리온': { slug: 'hyperion', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '아이스맨': { slug: 'iceman', originType: '일반캐', acquisitionType: '수정캐', upgradeLevel: '3티' },
  '이카리스': { slug: 'ikaris', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '인페르노': { slug: 'inferno', originType: '일반캐', upgradeLevel: '2티' },
  '인비저블 우먼': { slug: 'invisiblewoman', originType: '일반캐', acquisitionType: '디럭스', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '아이언 피스트': { slug: 'ironfist', originType: '일반캐', upgradeLevel: '각초' },
  '아이언 해머': { slug: 'ironhammer', originType: '일반캐', upgradeLevel: '각초' },
  '아이언하트': { slug: 'ironheart', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '아이언맨': { slug: 'ironman', iconUniformNumber: 10, originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '제인 포스터': { slug: 'janefoster', originType: '일반캐', upgradeLevel: '3티' },
  '진 그레이': { slug: 'jeangrey', originType: '태생캐 (2티, 더블)', acquisitionType: '엑조디아', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '제시카 존스': { slug: 'jessicajones', originType: '일반캐', upgradeLevel: '각초' },
  '주빌리': { slug: 'jubilee', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '저거너트': { slug: 'juggernaut', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '케실리우스': { slug: 'kaecilius', originType: '일반캐', upgradeLevel: '각초' },
  '케이티': { slug: 'katy', originType: '일반캐', upgradeLevel: '각초' },
  '카말라 칸': { slug: 'kamalakhan', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '카르낙': { slug: 'karnak', originType: '일반캐', upgradeLevel: '각초' },
  '정복자 캉': { slug: 'kang', originType: '태생캐 (3티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '케이트 비숍': { slug: 'katebishop', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '키드 카이쥬': { slug: 'kidkaiju', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '2티' },
  '키드 오메가': { slug: 'kidomega', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '킬몽거': { slug: 'killmonger', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '킨고': { slug: 'kingo', originType: '일반캐', upgradeLevel: '각초' },
  '킹핀': { slug: 'kingpin', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '키티 프라이드': { slug: 'kittypryde', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '널': { slug: 'knull', originType: '태생캐 (3티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '코라스': { slug: 'korath', originType: '일반캐', upgradeLevel: '각초' },
  '크레이븐': { slug: 'kraventhehunter', originType: '일반캐', upgradeLevel: '각초' },
  '래쉬': { slug: 'lash', originType: '일반캐', upgradeLevel: '각초' },
  '링컨 캠벨': { slug: 'lincolncampbell', originType: '일반캐', upgradeLevel: '각초' },
  '리자드': { slug: 'lizard', originType: '일반캐', upgradeLevel: '각초' },
  '로키': { slug: 'loki', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '루크 케이지': { slug: 'lukecage', originType: '일반캐', upgradeLevel: '각초' },
  '루나 스노우': { slug: 'lunasnow', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '매직': { slug: 'magik', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '매그니토': { slug: 'magneto', originType: '일반캐', acquisitionType: '디럭스', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '마카리': { slug: 'makkari', originType: '일반캐', acquisitionType: '디럭스', upgradeLevel: '각초' },
  '말레키스': { slug: 'malekith', originType: '일반캐', upgradeLevel: '각초' },
  '맨티스': { slug: 'mantis', originType: '일반캐', upgradeLevel: '각초' },
  '막시무스': { slug: 'maximus', originType: '일반캐', upgradeLevel: '각초' },
  '메두사': { slug: 'medusa', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '메피스토': { slug: 'mephisto', originType: '태생캐 (3티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '마일즈 모랄레스': { slug: 'milesmorales', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '미네-르바': { slug: 'minn-erva', originType: '일반캐', upgradeLevel: '각초' },
  '미스터 판타스틱': { slug: 'misterfantastic', originType: '태생캐 (2티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '미스터 시니스터': { slug: 'mistersinister', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '미스티 나이트': { slug: 'mistyknight', originType: '일반캐', upgradeLevel: '각초' },
  '모킹버드': { slug: 'mockingbird', originType: '일반캐', upgradeLevel: '각초' },
  'M.O.D.O.K.': { slug: 'modok', originType: '일반캐' },
  '몰큘맨': { slug: 'moleculeman', originType: '태생캐 (2티, 더블)', acquisitionType: '엑조디아', upgradeLevel: '3티' },
  '몰튼맨': { slug: 'moltenman', originType: '일반캐', upgradeLevel: '각초' },
  '문 걸': { slug: 'moongirl', originType: '일반캐', upgradeLevel: '각초' },
  '문 나이트': { slug: 'moonknight', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '문스톤': { slug: 'moonstone', originType: '일반캐', acquisitionType: '디럭스', upgradeLevel: '각초' },
  '모비어스': { slug: 'morbius', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '모건 르 페이': { slug: 'morganlefay', originType: '일반캐', upgradeLevel: '3티' },
  '미스테리오': { slug: 'mysterio', originType: '일반캐', upgradeLevel: '각초' },
  '미스틱': { slug: 'mystique', originType: '일반캐', acquisitionType: '수정캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '나디아 반 다인': { slug: 'nadiavandyne', originType: '일반캐', upgradeLevel: '각초' },
  '네이머': { slug: 'namor', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '네뷸라': { slug: 'nebula', originType: '일반캐', upgradeLevel: '각초' },
  '네가소닉 틴에이지 워헤드': { slug: 'negasonicteenagewarhead', originType: '일반캐', acquisitionType: '수정캐', upgradeLevel: '각초' },
  '닉 퓨리': { slug: 'nickfury', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '나이트크롤러': { slug: 'nightcrawler', originType: '일반캐', upgradeLevel: '각초' },
  '오딘': { slug: 'odin', originType: '태생캐 (2티, 더블)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '필 콜슨': { slug: 'philcoulson', originType: '일반캐', upgradeLevel: '3티' },
  '파일라-벨': { slug: 'phylavell', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '프로페서 X': { slug: 'professorx', originType: '일반캐', acquisitionType: '수정캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '프록시마 미드나이트': { slug: 'proximamidnight', originType: '태생캐 (2티)', upgradeLevel: '3티' },
  '사일록': { slug: 'psylocke', originType: '일반캐', acquisitionType: '디럭스', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '퍼니셔': { slug: 'punisher', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '퀵실버': { slug: 'quicksilver', originType: '태생캐 (2티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '레이첼 서머스': { slug: 'rachelsummers', originType: '일반캐', acquisitionType: '수정캐', upgradeLevel: '각초' },
  '레드 가디언': { slug: 'redguardian', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '레드헐크': { slug: 'redhulk', originType: '일반캐', upgradeLevel: '각초' },
  '레드 쉬-헐크': { slug: 'redshehulk', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '레드 스컬': { slug: 'redskull', originType: '일반캐', upgradeLevel: '각초' },
  '레스큐': { slug: 'rescue', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '라이노': { slug: 'rhino', originType: '일반캐', upgradeLevel: '각초' },
  '로비 레예스': { slug: 'robbiereyes', originType: '일반캐', upgradeLevel: '각초' },
  '로켓 라쿤': { slug: 'rocketraccoon', originType: '일반캐', upgradeLevel: '3티' },
  '로그': { slug: 'rogue', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '로난': { slug: 'ronan', originType: '일반캐', upgradeLevel: '3티' },
  '세이버투스': { slug: 'sabretooth', originType: '일반캐', acquisitionType: '수정캐', upgradeLevel: '3티' },
  '샘 알렉산더': { slug: 'samalexander', originType: '일반캐', upgradeLevel: '각초' },
  '샌드맨': { slug: 'sandman', originType: '일반캐', upgradeLevel: '각초' },
  '사타나': { slug: 'satana', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '스칼렛 스파이더': { slug: 'scarletspider', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '스칼렛 위치': { slug: 'scarletwitch', originType: '태생캐 (2티, 더블)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '스콜피온': { slug: 'scorpion', originType: '일반캐', upgradeLevel: '각초' },
  '스크림': { slug: 'scream', originType: '일반캐', upgradeLevel: '각초' },
  '센티넬': { slug: 'sentinel', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '센트리': { slug: 'sentry', originType: '태생캐 (3티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '세르시': { slug: 'sersi', originType: '일반캐', upgradeLevel: '각초' },
  '섀도우 셸': { slug: 'shadowshell', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '샹치': { slug: 'shangchi', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '에이전트 13': { slug: 'sharoncarter', originType: '일반캐', upgradeLevel: '각초' },
  '샤론 로저스': { slug: 'sharonrogers', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '쉬헐크': { slug: 'shehulk', originType: '일반캐', upgradeLevel: '3티' },
  '슈리': { slug: 'shuri', originType: '일반캐', upgradeLevel: '3티' },
  '시프': { slug: 'sif', originType: '일반캐', upgradeLevel: '각초' },
  '실크': { slug: 'silk', originType: '일반캐', upgradeLevel: '각초' },
  '실버 서퍼': { slug: 'silversurfer', originType: '태생캐 (2티, 더블)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '싱귤래리티': { slug: 'singularity', originType: '일반캐', upgradeLevel: '2티' },
  '시스터 그림': { slug: 'sistergrimm', originType: '일반캐', upgradeLevel: '3티' },
  '스커지': { slug: 'skurge', originType: '일반캐', upgradeLevel: '각초' },
  '슬랩스틱': { slug: 'slapstick', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '송버드': { slug: 'songbird', originType: '일반캐', upgradeLevel: '2티' },
  '스펙트럼': { slug: 'spectrum', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '스파이더 그웬': { slug: 'spidergwen', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '스파이더맨': { slug: 'spiderman', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '스파이더 우먼': { slug: 'spiderwoman', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '스쿼럴 걸': { slug: 'squirrelgirl', originType: '일반캐', upgradeLevel: '3티' },
  '스타 로드': { slug: 'starlord', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '스톰': { slug: 'storm', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '스트라이프': { slug: 'stryfe', originType: '태생캐 (2티, 더블)', acquisitionType: '엑조디아', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '썬 버드': { slug: 'sunbird', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '슈퍼자이언트': { slug: 'supergiant', originType: '태생캐 (2티)' },
  '소드마스터': { slug: 'swordmaster', originType: '일반캐', upgradeLevel: '각초' },
  '태스크마스터': { slug: 'taskmaster', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '테인': { slug: 'thane', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '타노스': { slug: 'thanos', iconUniformNumber: 6, originType: '태생캐 (2티, 더블)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '테나': { slug: 'thena', originType: '일반캐', acquisitionType: '엑조디아', upgradeLevel: '3티' },
  '씽': { slug: 'thing', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '토르': { slug: 'thor', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '타이타니아': { slug: 'titania', originType: '일반캐', upgradeLevel: '각초' },
  '율리크': { slug: 'ulik', originType: '일반캐', upgradeLevel: '각초' },
  '울트론': { slug: 'ultron', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '율리시스 클로': { slug: 'ulyssesklaue', originType: '일반캐', upgradeLevel: '2티' },
  '발키리': { slug: 'valkyrie', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '베놈': { slug: 'venom', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '빅토리어스': { slug: 'victorious', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '바이퍼': { slug: 'viper', originType: '일반캐', upgradeLevel: '2티' },
  '비전': { slug: 'vision', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '볼스탁': { slug: 'volstagg', originType: '일반캐', upgradeLevel: '각초' },
  '벌쳐': { slug: 'vulture', originType: '일반캐', upgradeLevel: '각초' },
  '워머신': { slug: 'warmachine', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '워패스': { slug: 'warpath', originType: '일반캐', upgradeLevel: '각초' },
  '워 타이거': { slug: 'wartiger', originType: '일반캐', upgradeLevel: '각초' },
  '워울프': { slug: 'warwolf', originType: '일반캐', upgradeLevel: '각초' },
  '와스프': { slug: 'wasp', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '웨이브': { slug: 'wave', originType: '일반캐', acquisitionType: '수정캐', upgradeLevel: '각초' },
  '웨폰 헥스': { slug: 'weaponhex', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '웬우': { slug: 'wenwu', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '화이트 폭스': { slug: 'whitefox', originType: '일반캐', upgradeLevel: '3티' },
  '화이트 타이거': { slug: 'whitetiger', originType: '일반캐', upgradeLevel: '각초' },
  '위칸': { slug: 'wiccan', originType: '일반캐', upgradeLevel: '각초' },
  '위플래쉬': { slug: 'whiplash', originType: '일반캐', upgradeLevel: '2티' },
  '윈터 솔져': { slug: 'wintersoldier', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '울버린': { slug: 'wolverine', originType: '태생캐 (2티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '아테나': { slug: 'athena', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '블랙 나이트': { slug: 'blackknight', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '캐시 랭': { slug: 'cassielang', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '카산드라 노바': { slug: 'cassandranova', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '엑소더스': { slug: 'exodus', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '프랭클린 리처즈': { slug: 'franklinrichards', originType: '일반캐', upgradeLevel: '각초' },
  '플루토': { slug: 'hades', originType: '일반캐', acquisitionType: '디럭스', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '하복': { slug: 'havok', originType: '태생캐 (2티)', upgradeLevel: '3티' },
  '헤라클레스': { slug: 'hercules', originType: '태생캐 (2티)', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '호프 서머스': { slug: 'hopesummers', originType: '일반캐', acquisitionType: '디럭스', upgradeLevel: '각초' },
  '더 후드': { slug: 'thehood', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '아이콘': { slug: 'ikon', originType: '일반캐', upgradeLevel: '각초' },
  '호아킨 토레스': { slug: 'joaquintorres', originType: '일반캐', upgradeLevel: '3티' },
  '카호리': { slug: 'kahhori', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '리더': { slug: 'leader', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '매들린 프라이어': { slug: 'madelynepryor', originType: '태생캐 (2티, 더블)', acquisitionType: '엑조디아', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '맨-씽': { slug: 'manthing', originType: '일반캐', upgradeLevel: '각초' },
  '마블 보이': { slug: 'marvelboy', originType: '일반캐', upgradeLevel: '3티' },
  '음바쿠': { slug: 'mbaku', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '오코예': { slug: 'okoye', originType: '일반캐', upgradeLevel: '3티' },
  '오메가 레드': { slug: 'omegared', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '폴라리스': { slug: 'polaris', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '샬라-발': { slug: 'shallabal', originType: '태생캐 (2티, 더블)', acquisitionType: '수정캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '실버 사무라이': { slug: 'silversamurai', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '슬리퍼': { slug: 'sleeper', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '신': { slug: 'sin', originType: '일반캐', upgradeLevel: '3티' },
  '스팟': { slug: 'spot', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '선스팟': { slug: 'sunspot', originType: '일반캐', upgradeLevel: '3티' },
  '실비': { slug: 'sylvie', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '톡신': { slug: 'toxin', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  'U.S.에이전트': { slug: 'usagent', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
  '발레리아 리처즈': { slug: 'valeriarichards', originType: '일반캐', upgradeLevel: '각초' },
  '아프로디테': { slug: 'venus', originType: '일반캐', upgradeLevel: '각초' },
  '웬델 본': { slug: 'wendellvaughn', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '웡': { slug: 'wong', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '옐레나 벨로바': { slug: 'yelenabelova', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '4티', baseUpgradeLevel: '각초' },
  '옐로우 재킷': { slug: 'yellowjacket', originType: '일반캐', upgradeLevel: '각초' },
  '욘두': { slug: 'yondu', originType: '일반캐', upgradeLevel: '3티' },
  '제우스': { slug: 'zeus', originType: '태생캐 (2티, 더블)', acquisitionType: '엑조디아', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '아마데우스 조': { slug: 'amadeuscho', originType: '일반캐', upgradeLevel: '각초' },
  '에이브릴 킨케이드': { slug: 'quasar', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '각초' },
  '리처드 라이더': { slug: 'nova', originType: '일반캐', acquisitionType: '디럭스', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  'X-23': { slug: 'x-23', originType: '일반캐', upgradeLevel: '4티', baseUpgradeLevel: '3티' },
  '스파이더맨 2099': { slug: 'spiderman2099', originType: '일반캐', acquisitionType: '매생/매엑', upgradeLevel: '3티' },
};


export const characterNames = Object.keys(characterData).sort((a, b) => a.localeCompare(b, 'ko'));
export const ORIGIN_TYPES = ['일반캐', '태생캐 (2티)', '태생캐 (2티, 더블)', '태생캐 (3티)'];

export function isValidCharacter(name) {
  return characterNames.includes(name);
}

export function isValidOriginType(originType) {
  return ORIGIN_TYPES.includes(originType);
}
